//
//  FavoriteViewControllerExtension.swift
//  MovieSearch
//
//  Created by Kirill G on 7/22/18.
//  Copyright © 2018 ns-ios. All rights reserved.
//

import Foundation
import UIKit
import Firebase
import FirebaseAuth

extension FavoriteViewController: UITableViewDataSource, UITableViewDelegate {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return favoriteMovies.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "favCell")
        
        cell?.textLabel?.text = favoriteMovies[indexPath.row]
        
        return cell!
    }
    
    func tableView(_ tableView: UITableView, canEditRowAt indexPath: IndexPath) -> Bool {
        return true
    }
    
    func tableView(_ tableView: UITableView, commit editingStyle: UITableViewCellEditingStyle, forRowAt indexPath: IndexPath) {
        if editingStyle == .delete {
            getMovieKeys()
            
            let when = DispatchTime.now() + 1
            DispatchQueue.main.asyncAfter(deadline: when, execute: {
                self.ref.child(Constants.folderName).child(self.movieKeys[indexPath.row]).removeValue()
                self.favoriteMovies.remove(at: indexPath.row)
                self.movieKeys = []
            })
        }
    }
    
    // To get all keys generated by childByAutoId
    func getMovieKeys() {
        ref?.child(Constants.folderName).observeSingleEvent(of: .value, with: { (snapshot) in
            for child in snapshot.children {
                let snap = child as! DataSnapshot
                let key = snap.key
                self.movieKeys.append(key)
            }
        })
    }

}
